
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mula-api-deployment
  labels:
    app: mula-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mula-api
  template:
    metadata:
      labels:
        app: mula-api
    spec:
      containers:
      - name: mula-api
        image: 195637673041.dkr.ecr.us-east-1.amazonaws.com/mula:d9185ddbc94496f804135bed3d560a7d964a55a8
        ports:
        - containerPort: 8080